---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: publish storybook image
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key
    secret_key:
      from_secret: aws_access_key_secret
    region: eu-west-1
    repo: drone/amazon-secrets
    registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
    dockerfile: docker/Dockerfile
    tags:
      - latest
      - ${CI_COMMIT_SHA}