---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build plugin
  image: golang:1.12
  commands:
  #- go test -v -cover ./...
  - CGO_ENABLED=0 go build -o release/linux/amd64/drone-amazon-secrets github.com/BerlingskeMedia/drone-amazon-secrets/tree/master/cmd/drone-amazon-secrets

- name: publish amazon-secrets image
  image: plugins/ecr
  settings:
    access_key:
      from_secret: aws_access_key
    secret_key:
      from_secret: aws_access_key_secret
    region: eu-west-1
    repo: drone/amazon-secrets
    registry: 815296035528.dkr.ecr.eu-west-1.amazonaws.com
    dockerfile: docker/Dockerfile
    tags:
      - latest
      - ${CI_COMMIT_SHA}